/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_STEAM_MESSAGES_PB_H_INCLUDED
#define PB_STEAM_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _CMsgProtoBufHeader_ESessionDisposition {
    CMsgProtoBufHeader_ESessionDisposition_k_ESessionDispositionNormal = 0,
    CMsgProtoBufHeader_ESessionDisposition_k_ESessionDispositionDisconnect = 1
} CMsgProtoBufHeader_ESessionDisposition;

/* Struct definitions */
/* ============================================================
 CMsgProtoBufHeader
 ============================================================ */
typedef struct _CMsgGCRoutingProtoBufHeader {
    bool has_dst_gcid_queue;
    uint64_t dst_gcid_queue;
    bool has_dst_gc_dir_index;
    uint32_t dst_gc_dir_index;
} CMsgGCRoutingProtoBufHeader;

typedef struct _CMsgProtoBufHeader {
    bool has_steamid;
    uint64_t steamid;
    bool has_client_sessionid;
    int32_t client_sessionid;
    bool has_routing_appid;
    uint32_t routing_appid;
    bool has_jobid_source;
    uint64_t jobid_source;
    bool has_jobid_target;
    uint64_t jobid_target;
    bool has_target_job_name;
    char target_job_name[128];
    bool has_eresult;
    int32_t eresult;
    pb_size_t which_ip_addr;
    union {
        uint32_t ip;
    } ip_addr;
    bool has_auth_account_flags;
    uint32_t auth_account_flags;
    bool has_transport_error;
    int32_t transport_error;
    bool has_messageid;
    uint64_t messageid;
    bool has_publisher_group_id;
    uint32_t publisher_group_id;
    bool has_sysid;
    uint32_t sysid;
    bool has_trace_tag;
    uint64_t trace_tag;
    bool has_token_source;
    uint32_t token_source;
    bool has_admin_spoofing_user;
    bool admin_spoofing_user;
    bool has_seq_num;
    int32_t seq_num;
    bool has_webapi_key_id;
    uint32_t webapi_key_id;
    bool has_is_from_external_source;
    bool is_from_external_source;
    bool has_cm_sysid;
    uint32_t cm_sysid;
    bool has_launcher_type;
    uint32_t launcher_type;
    bool has_realm;
    uint32_t realm;
    bool has_timeout_ms;
    int32_t timeout_ms;
    bool has_debug_source_string_index;
    uint32_t debug_source_string_index;
    bool has_token_id;
    uint64_t token_id;
    bool has_routing_gc;
    CMsgGCRoutingProtoBufHeader routing_gc;
    bool has_session_disposition;
    CMsgProtoBufHeader_ESessionDisposition session_disposition;
} CMsgProtoBufHeader;

typedef PB_BYTES_ARRAY_T(1024) EncryptedAppTicket_encrypted_ticket_t;
typedef struct _EncryptedAppTicket {
    bool has_ticket_version_no;
    uint32_t ticket_version_no;
    bool has_crc_encryptedticket;
    uint32_t crc_encryptedticket;
    bool has_cb_encrypteduserdata;
    uint32_t cb_encrypteduserdata;
    bool has_cb_encrypted_appownershipticket;
    uint32_t cb_encrypted_appownershipticket;
    bool has_encrypted_ticket;
    EncryptedAppTicket_encrypted_ticket_t encrypted_ticket;
} EncryptedAppTicket;

typedef struct _CMsgClientRequestEncryptedAppTicketResponse {
    bool has_app_id;
    uint32_t app_id;
    bool has_eresult;
    int32_t eresult;
    bool has_encrypted_app_ticket;
    EncryptedAppTicket encrypted_app_ticket;
} CMsgClientRequestEncryptedAppTicketResponse;

/* ============================================================
 CMsgClientPICSProductInfoRequest  (eMsg 8903)
 ============================================================ */
typedef struct _CMsgClientPICSProductInfoRequest {
    pb_callback_t packages;
    pb_callback_t apps;
    bool has_meta_data_only;
    bool meta_data_only;
    bool has_num_prev_failed;
    uint32_t num_prev_failed;
    bool has_supports_package_tokens;
    uint32_t supports_package_tokens;
} CMsgClientPICSProductInfoRequest;

typedef struct _CMsgClientPICSProductInfoRequest_AppInfo {
    bool has_appid;
    uint32_t appid;
    bool has_access_token;
    uint64_t access_token;
    bool has_only_public_obsolete;
    bool only_public_obsolete;
} CMsgClientPICSProductInfoRequest_AppInfo;

typedef struct _CMsgClientPICSProductInfoRequest_PackageInfo {
    bool has_packageid;
    uint32_t packageid;
    bool has_access_token;
    uint64_t access_token;
} CMsgClientPICSProductInfoRequest_PackageInfo;

/* ============================================================
 CFamilyGroupsClient_NotifyRunningApps_Notification  (eMsg 147 target_job_name)
 ============================================================ */
typedef struct _CFamilyGroupsClient_NotifyRunningApps_Notification {
    bool has_family_groupid;
    uint64_t family_groupid;
    pb_callback_t running_apps;
} CFamilyGroupsClient_NotifyRunningApps_Notification;

typedef struct _CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember {
    bool has_member_steamid;
    uint64_t member_steamid;
    bool has_owner_steamid;
    uint64_t owner_steamid;
} CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember;

typedef struct _CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp {
    bool has_appid;
    uint32_t appid;
    bool has_is_locked;
    bool is_locked;
    pb_callback_t playing_members;
} CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp;

/* ============================================================
 CMsgClientSharedLibraryStopPlaying  (eMsg 9406)
 ============================================================ */
typedef struct _CMsgClientSharedLibraryStopPlaying {
    bool has_seconds_left;
    int32_t seconds_left;
    pb_callback_t stop_apps;
} CMsgClientSharedLibraryStopPlaying;

typedef struct _CMsgClientSharedLibraryStopPlaying_StopApp {
    bool has_app_id;
    uint32_t app_id;
    bool has_owner_id;
    uint32_t owner_id;
} CMsgClientSharedLibraryStopPlaying_StopApp;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _CMsgProtoBufHeader_ESessionDisposition_MIN CMsgProtoBufHeader_ESessionDisposition_k_ESessionDispositionNormal
#define _CMsgProtoBufHeader_ESessionDisposition_MAX CMsgProtoBufHeader_ESessionDisposition_k_ESessionDispositionDisconnect
#define _CMsgProtoBufHeader_ESessionDisposition_ARRAYSIZE ((CMsgProtoBufHeader_ESessionDisposition)(CMsgProtoBufHeader_ESessionDisposition_k_ESessionDispositionDisconnect+1))


#define CMsgProtoBufHeader_session_disposition_ENUMTYPE CMsgProtoBufHeader_ESessionDisposition












/* Initializer values for message structs */
#define CMsgGCRoutingProtoBufHeader_init_default {false, 0, false, 0}
#define CMsgProtoBufHeader_init_default          {false, 0, false, 0, false, 0, false, 18446744073709551615ull, false, 18446744073709551615ull, false, "", false, 2, 0, {0}, false, 0, false, 1, false, 18446744073709551615ull, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0u, false, 0u, false, -1, false, 0, false, 0, false, CMsgGCRoutingProtoBufHeader_init_default, false, CMsgProtoBufHeader_ESessionDisposition_k_ESessionDispositionNormal}
#define EncryptedAppTicket_init_default          {false, 0, false, 0, false, 0, false, 0, false, {0, {0}}}
#define CMsgClientRequestEncryptedAppTicketResponse_init_default {false, 0, false, 2, false, EncryptedAppTicket_init_default}
#define CMsgClientPICSProductInfoRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0}
#define CMsgClientPICSProductInfoRequest_AppInfo_init_default {false, 0, false, 0, false, 0}
#define CMsgClientPICSProductInfoRequest_PackageInfo_init_default {false, 0, false, 0}
#define CFamilyGroupsClient_NotifyRunningApps_Notification_init_default {false, 0, {{NULL}, NULL}}
#define CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember_init_default {false, 0, false, 0}
#define CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp_init_default {false, 0, false, 0, {{NULL}, NULL}}
#define CMsgClientSharedLibraryStopPlaying_init_default {false, 0, {{NULL}, NULL}}
#define CMsgClientSharedLibraryStopPlaying_StopApp_init_default {false, 0, false, 0}
#define CMsgGCRoutingProtoBufHeader_init_zero    {false, 0, false, 0}
#define CMsgProtoBufHeader_init_zero             {false, 0, false, 0, false, 0, false, 0, false, 0, false, "", false, 0, 0, {0}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, CMsgGCRoutingProtoBufHeader_init_zero, false, _CMsgProtoBufHeader_ESessionDisposition_MIN}
#define EncryptedAppTicket_init_zero             {false, 0, false, 0, false, 0, false, 0, false, {0, {0}}}
#define CMsgClientRequestEncryptedAppTicketResponse_init_zero {false, 0, false, 0, false, EncryptedAppTicket_init_zero}
#define CMsgClientPICSProductInfoRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0}
#define CMsgClientPICSProductInfoRequest_AppInfo_init_zero {false, 0, false, 0, false, 0}
#define CMsgClientPICSProductInfoRequest_PackageInfo_init_zero {false, 0, false, 0}
#define CFamilyGroupsClient_NotifyRunningApps_Notification_init_zero {false, 0, {{NULL}, NULL}}
#define CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember_init_zero {false, 0, false, 0}
#define CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp_init_zero {false, 0, false, 0, {{NULL}, NULL}}
#define CMsgClientSharedLibraryStopPlaying_init_zero {false, 0, {{NULL}, NULL}}
#define CMsgClientSharedLibraryStopPlaying_StopApp_init_zero {false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define CMsgGCRoutingProtoBufHeader_dst_gcid_queue_tag 1
#define CMsgGCRoutingProtoBufHeader_dst_gc_dir_index_tag 2
#define CMsgProtoBufHeader_steamid_tag           1
#define CMsgProtoBufHeader_client_sessionid_tag  2
#define CMsgProtoBufHeader_routing_appid_tag     3
#define CMsgProtoBufHeader_jobid_source_tag      10
#define CMsgProtoBufHeader_jobid_target_tag      11
#define CMsgProtoBufHeader_target_job_name_tag   12
#define CMsgProtoBufHeader_eresult_tag           13
#define CMsgProtoBufHeader_ip_tag                15
#define CMsgProtoBufHeader_auth_account_flags_tag 16
#define CMsgProtoBufHeader_transport_error_tag   17
#define CMsgProtoBufHeader_messageid_tag         18
#define CMsgProtoBufHeader_publisher_group_id_tag 19
#define CMsgProtoBufHeader_sysid_tag             20
#define CMsgProtoBufHeader_trace_tag_tag         21
#define CMsgProtoBufHeader_token_source_tag      22
#define CMsgProtoBufHeader_admin_spoofing_user_tag 23
#define CMsgProtoBufHeader_seq_num_tag           24
#define CMsgProtoBufHeader_webapi_key_id_tag     25
#define CMsgProtoBufHeader_is_from_external_source_tag 26
#define CMsgProtoBufHeader_cm_sysid_tag          28
#define CMsgProtoBufHeader_launcher_type_tag     31
#define CMsgProtoBufHeader_realm_tag             32
#define CMsgProtoBufHeader_timeout_ms_tag        33
#define CMsgProtoBufHeader_debug_source_string_index_tag 35
#define CMsgProtoBufHeader_token_id_tag          36
#define CMsgProtoBufHeader_routing_gc_tag        37
#define CMsgProtoBufHeader_session_disposition_tag 38
#define EncryptedAppTicket_ticket_version_no_tag 1
#define EncryptedAppTicket_crc_encryptedticket_tag 2
#define EncryptedAppTicket_cb_encrypteduserdata_tag 3
#define EncryptedAppTicket_cb_encrypted_appownershipticket_tag 4
#define EncryptedAppTicket_encrypted_ticket_tag  5
#define CMsgClientRequestEncryptedAppTicketResponse_app_id_tag 1
#define CMsgClientRequestEncryptedAppTicketResponse_eresult_tag 2
#define CMsgClientRequestEncryptedAppTicketResponse_encrypted_app_ticket_tag 3
#define CMsgClientPICSProductInfoRequest_packages_tag 1
#define CMsgClientPICSProductInfoRequest_apps_tag 2
#define CMsgClientPICSProductInfoRequest_meta_data_only_tag 3
#define CMsgClientPICSProductInfoRequest_num_prev_failed_tag 4
#define CMsgClientPICSProductInfoRequest_supports_package_tokens_tag 5
#define CMsgClientPICSProductInfoRequest_AppInfo_appid_tag 1
#define CMsgClientPICSProductInfoRequest_AppInfo_access_token_tag 2
#define CMsgClientPICSProductInfoRequest_AppInfo_only_public_obsolete_tag 3
#define CMsgClientPICSProductInfoRequest_PackageInfo_packageid_tag 1
#define CMsgClientPICSProductInfoRequest_PackageInfo_access_token_tag 2
#define CFamilyGroupsClient_NotifyRunningApps_Notification_family_groupid_tag 1
#define CFamilyGroupsClient_NotifyRunningApps_Notification_running_apps_tag 2
#define CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember_member_steamid_tag 1
#define CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember_owner_steamid_tag 2
#define CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp_appid_tag 1
#define CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp_is_locked_tag 2
#define CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp_playing_members_tag 3
#define CMsgClientSharedLibraryStopPlaying_seconds_left_tag 1
#define CMsgClientSharedLibraryStopPlaying_stop_apps_tag 2
#define CMsgClientSharedLibraryStopPlaying_StopApp_app_id_tag 1
#define CMsgClientSharedLibraryStopPlaying_StopApp_owner_id_tag 2

/* Struct field encoding specification for nanopb */
#define CMsgGCRoutingProtoBufHeader_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   dst_gcid_queue,    1) \
X(a, STATIC,   OPTIONAL, UINT32,   dst_gc_dir_index,   2)
#define CMsgGCRoutingProtoBufHeader_CALLBACK NULL
#define CMsgGCRoutingProtoBufHeader_DEFAULT NULL

#define CMsgProtoBufHeader_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FIXED64,  steamid,           1) \
X(a, STATIC,   OPTIONAL, INT32,    client_sessionid,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   routing_appid,     3) \
X(a, STATIC,   OPTIONAL, FIXED64,  jobid_source,     10) \
X(a, STATIC,   OPTIONAL, FIXED64,  jobid_target,     11) \
X(a, STATIC,   OPTIONAL, STRING,   target_job_name,  12) \
X(a, STATIC,   OPTIONAL, INT32,    eresult,          13) \
X(a, STATIC,   ONEOF,    UINT32,   (ip_addr,ip,ip_addr.ip),  15) \
X(a, STATIC,   OPTIONAL, UINT32,   auth_account_flags,  16) \
X(a, STATIC,   OPTIONAL, INT32,    transport_error,  17) \
X(a, STATIC,   OPTIONAL, UINT64,   messageid,        18) \
X(a, STATIC,   OPTIONAL, UINT32,   publisher_group_id,  19) \
X(a, STATIC,   OPTIONAL, UINT32,   sysid,            20) \
X(a, STATIC,   OPTIONAL, UINT64,   trace_tag,        21) \
X(a, STATIC,   OPTIONAL, UINT32,   token_source,     22) \
X(a, STATIC,   OPTIONAL, BOOL,     admin_spoofing_user,  23) \
X(a, STATIC,   OPTIONAL, INT32,    seq_num,          24) \
X(a, STATIC,   OPTIONAL, UINT32,   webapi_key_id,    25) \
X(a, STATIC,   OPTIONAL, BOOL,     is_from_external_source,  26) \
X(a, STATIC,   OPTIONAL, UINT32,   cm_sysid,         28) \
X(a, STATIC,   OPTIONAL, UINT32,   launcher_type,    31) \
X(a, STATIC,   OPTIONAL, UINT32,   realm,            32) \
X(a, STATIC,   OPTIONAL, INT32,    timeout_ms,       33) \
X(a, STATIC,   OPTIONAL, UINT32,   debug_source_string_index,  35) \
X(a, STATIC,   OPTIONAL, UINT64,   token_id,         36) \
X(a, STATIC,   OPTIONAL, MESSAGE,  routing_gc,       37) \
X(a, STATIC,   OPTIONAL, UENUM,    session_disposition,  38)
#define CMsgProtoBufHeader_CALLBACK NULL
#define CMsgProtoBufHeader_DEFAULT (const pb_byte_t*)"\x51\xff\xff\xff\xff\xff\xff\xff\xff\x59\xff\xff\xff\xff\xff\xff\xff\xff\x68\x02\x88\x01\x01\x90\x01\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\xf8\x01\x00\x80\x02\x00\x88\x02\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x00"
#define CMsgProtoBufHeader_routing_gc_MSGTYPE CMsgGCRoutingProtoBufHeader

#define EncryptedAppTicket_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   ticket_version_no,   1) \
X(a, STATIC,   OPTIONAL, UINT32,   crc_encryptedticket,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   cb_encrypteduserdata,   3) \
X(a, STATIC,   OPTIONAL, UINT32,   cb_encrypted_appownershipticket,   4) \
X(a, STATIC,   OPTIONAL, BYTES,    encrypted_ticket,   5)
#define EncryptedAppTicket_CALLBACK NULL
#define EncryptedAppTicket_DEFAULT NULL

#define CMsgClientRequestEncryptedAppTicketResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   app_id,            1) \
X(a, STATIC,   OPTIONAL, INT32,    eresult,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  encrypted_app_ticket,   3)
#define CMsgClientRequestEncryptedAppTicketResponse_CALLBACK NULL
#define CMsgClientRequestEncryptedAppTicketResponse_DEFAULT (const pb_byte_t*)"\x10\x02\x00"
#define CMsgClientRequestEncryptedAppTicketResponse_encrypted_app_ticket_MSGTYPE EncryptedAppTicket

#define CMsgClientPICSProductInfoRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  packages,          1) \
X(a, CALLBACK, REPEATED, MESSAGE,  apps,              2) \
X(a, STATIC,   OPTIONAL, BOOL,     meta_data_only,    3) \
X(a, STATIC,   OPTIONAL, UINT32,   num_prev_failed,   4) \
X(a, STATIC,   OPTIONAL, UINT32,   supports_package_tokens,   5)
#define CMsgClientPICSProductInfoRequest_CALLBACK pb_default_field_callback
#define CMsgClientPICSProductInfoRequest_DEFAULT NULL
#define CMsgClientPICSProductInfoRequest_packages_MSGTYPE CMsgClientPICSProductInfoRequest_PackageInfo
#define CMsgClientPICSProductInfoRequest_apps_MSGTYPE CMsgClientPICSProductInfoRequest_AppInfo

#define CMsgClientPICSProductInfoRequest_AppInfo_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   appid,             1) \
X(a, STATIC,   OPTIONAL, UINT64,   access_token,      2) \
X(a, STATIC,   OPTIONAL, BOOL,     only_public_obsolete,   3)
#define CMsgClientPICSProductInfoRequest_AppInfo_CALLBACK NULL
#define CMsgClientPICSProductInfoRequest_AppInfo_DEFAULT NULL

#define CMsgClientPICSProductInfoRequest_PackageInfo_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   packageid,         1) \
X(a, STATIC,   OPTIONAL, UINT64,   access_token,      2)
#define CMsgClientPICSProductInfoRequest_PackageInfo_CALLBACK NULL
#define CMsgClientPICSProductInfoRequest_PackageInfo_DEFAULT NULL

#define CFamilyGroupsClient_NotifyRunningApps_Notification_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   family_groupid,    1) \
X(a, CALLBACK, REPEATED, MESSAGE,  running_apps,      2)
#define CFamilyGroupsClient_NotifyRunningApps_Notification_CALLBACK pb_default_field_callback
#define CFamilyGroupsClient_NotifyRunningApps_Notification_DEFAULT NULL
#define CFamilyGroupsClient_NotifyRunningApps_Notification_running_apps_MSGTYPE CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp

#define CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FIXED64,  member_steamid,    1) \
X(a, STATIC,   OPTIONAL, FIXED64,  owner_steamid,     2)
#define CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember_CALLBACK NULL
#define CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember_DEFAULT NULL

#define CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   appid,             1) \
X(a, STATIC,   OPTIONAL, BOOL,     is_locked,         2) \
X(a, CALLBACK, REPEATED, MESSAGE,  playing_members,   3)
#define CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp_CALLBACK pb_default_field_callback
#define CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp_DEFAULT NULL
#define CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp_playing_members_MSGTYPE CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember

#define CMsgClientSharedLibraryStopPlaying_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    seconds_left,      1) \
X(a, CALLBACK, REPEATED, MESSAGE,  stop_apps,         2)
#define CMsgClientSharedLibraryStopPlaying_CALLBACK pb_default_field_callback
#define CMsgClientSharedLibraryStopPlaying_DEFAULT NULL
#define CMsgClientSharedLibraryStopPlaying_stop_apps_MSGTYPE CMsgClientSharedLibraryStopPlaying_StopApp

#define CMsgClientSharedLibraryStopPlaying_StopApp_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   app_id,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   owner_id,          2)
#define CMsgClientSharedLibraryStopPlaying_StopApp_CALLBACK NULL
#define CMsgClientSharedLibraryStopPlaying_StopApp_DEFAULT NULL

extern const pb_msgdesc_t CMsgGCRoutingProtoBufHeader_msg;
extern const pb_msgdesc_t CMsgProtoBufHeader_msg;
extern const pb_msgdesc_t EncryptedAppTicket_msg;
extern const pb_msgdesc_t CMsgClientRequestEncryptedAppTicketResponse_msg;
extern const pb_msgdesc_t CMsgClientPICSProductInfoRequest_msg;
extern const pb_msgdesc_t CMsgClientPICSProductInfoRequest_AppInfo_msg;
extern const pb_msgdesc_t CMsgClientPICSProductInfoRequest_PackageInfo_msg;
extern const pb_msgdesc_t CFamilyGroupsClient_NotifyRunningApps_Notification_msg;
extern const pb_msgdesc_t CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember_msg;
extern const pb_msgdesc_t CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp_msg;
extern const pb_msgdesc_t CMsgClientSharedLibraryStopPlaying_msg;
extern const pb_msgdesc_t CMsgClientSharedLibraryStopPlaying_StopApp_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CMsgGCRoutingProtoBufHeader_fields &CMsgGCRoutingProtoBufHeader_msg
#define CMsgProtoBufHeader_fields &CMsgProtoBufHeader_msg
#define EncryptedAppTicket_fields &EncryptedAppTicket_msg
#define CMsgClientRequestEncryptedAppTicketResponse_fields &CMsgClientRequestEncryptedAppTicketResponse_msg
#define CMsgClientPICSProductInfoRequest_fields &CMsgClientPICSProductInfoRequest_msg
#define CMsgClientPICSProductInfoRequest_AppInfo_fields &CMsgClientPICSProductInfoRequest_AppInfo_msg
#define CMsgClientPICSProductInfoRequest_PackageInfo_fields &CMsgClientPICSProductInfoRequest_PackageInfo_msg
#define CFamilyGroupsClient_NotifyRunningApps_Notification_fields &CFamilyGroupsClient_NotifyRunningApps_Notification_msg
#define CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember_fields &CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember_msg
#define CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp_fields &CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp_msg
#define CMsgClientSharedLibraryStopPlaying_fields &CMsgClientSharedLibraryStopPlaying_msg
#define CMsgClientSharedLibraryStopPlaying_StopApp_fields &CMsgClientSharedLibraryStopPlaying_StopApp_msg

/* Maximum encoded size of messages (where known) */
/* CMsgClientPICSProductInfoRequest_size depends on runtime parameters */
/* CFamilyGroupsClient_NotifyRunningApps_Notification_size depends on runtime parameters */
/* CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp_size depends on runtime parameters */
/* CMsgClientSharedLibraryStopPlaying_size depends on runtime parameters */
#define CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember_size 18
#define CMsgClientPICSProductInfoRequest_AppInfo_size 19
#define CMsgClientPICSProductInfoRequest_PackageInfo_size 17
#define CMsgClientRequestEncryptedAppTicketResponse_size 1071
#define CMsgClientSharedLibraryStopPlaying_StopApp_size 12
#define CMsgGCRoutingProtoBufHeader_size         17
#define CMsgProtoBufHeader_size                  355
#define EncryptedAppTicket_size                  1051
#define STEAM_MESSAGES_PB_H_MAX_SIZE             CMsgClientRequestEncryptedAppTicketResponse_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
