/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "steam_messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CMsgGCRoutingProtoBufHeader, CMsgGCRoutingProtoBufHeader, AUTO)


PB_BIND(CMsgProtoBufHeader, CMsgProtoBufHeader, 2)


PB_BIND(EncryptedAppTicket, EncryptedAppTicket, 2)


PB_BIND(CMsgClientRequestEncryptedAppTicketResponse, CMsgClientRequestEncryptedAppTicketResponse, 2)


PB_BIND(CMsgClientPICSProductInfoRequest, CMsgClientPICSProductInfoRequest, AUTO)


PB_BIND(CMsgClientPICSProductInfoRequest_AppInfo, CMsgClientPICSProductInfoRequest_AppInfo, AUTO)


PB_BIND(CMsgClientPICSProductInfoRequest_PackageInfo, CMsgClientPICSProductInfoRequest_PackageInfo, AUTO)


PB_BIND(CFamilyGroupsClient_NotifyRunningApps_Notification, CFamilyGroupsClient_NotifyRunningApps_Notification, AUTO)


PB_BIND(CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember, CFamilyGroupsClient_NotifyRunningApps_Notification_PlayingMember, AUTO)


PB_BIND(CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp, CFamilyGroupsClient_NotifyRunningApps_Notification_RunningApp, AUTO)


PB_BIND(CMsgClientSharedLibraryStopPlaying, CMsgClientSharedLibraryStopPlaying, AUTO)


PB_BIND(CMsgClientSharedLibraryStopPlaying_StopApp, CMsgClientSharedLibraryStopPlaying_StopApp, AUTO)





